version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root-postgres
      POSTGRES_PASSWORD: password-postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  # postgres_testing:
  #   container_name: postgres_tests_container
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: test-postgres
  #     POSTGRES_PASSWORD: password-postgres
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres-test:/data/postgres
  #   ports:
  #     - "5433:5432"

volumes: 
    postgres:
    postgres-test:
