version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root-postgres
      POSTGRES_PASSWORD: password-postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  server:
    build: .
    container_name: server_container
    depends_on:
       - postgres
    ports:
      - 3333:3333

volumes: 
    postgres:
